import React from 'react';
import Head from 'next/head'

const media = () => {

  return (
    <>
      < Head >
        <title>Media</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head >

      <div className='flex justify-center py-24'>
        <h2 className='text-2xl text-emerald-800 font bold'>Coming Soon...</h2>
      </div>
    </>
  );
};

export default media;